### ISSUE TITLE
MPW Link Error: Out of memory

### ISSUE THREAD

**Issue by steventroughtonsmith** [ksherlock/mpw#19]
When compiling the Desk Accessory MPW sample project, Link errors out with
```
### Link: Error: Out of memory: unable to allocate resource buffer. (Error 27)  for largest module 
### Link: Errors prevented normal completion.
```

The --ram flag for mpw doesn't seem to affect this. Project attached (verified to compile in a real MPW install)

https://gist.github.com/steventroughtonsmith/5ad1ac4ebbf883de05b1

**Comment by ksherlock** [comment]
92d465fb56da1366a0b506cc012c83294376b9f0 should fix it.

**Comment by steventroughtonsmith** [comment]
Verified fixed!
