### ISSUE TITLE
MPW PascalIIGS 

### ISSUE THREAD

**Issue by steventroughtonsmith** [ksherlock/mpw#20]
MPW PascalIIGS isn't quite there yet.
```
Unsupported tool trap: aded ((null))
```

Sample project (requires MPW PascalIIGS & co): https://gist.github.com/steventroughtonsmith/8043130cea031f9ef8fe

**Comment by ksherlock** [comment]
Are you using Pascal IIgs 1.0 (or earlier?)  I can build it (once the code is updated a bit) with more recent versions.

    MPW IIGS C Compiler -- Version 1.1d5, Feb 26 1992
    Copyright Apple Computer Inc. and Megamax, Inc. 1986-1990
    All Rights Reserved

    MPW Pascal IIGS Cross Compiler, Release 1.1, Built on 2/12/92 6:18:53 PM
    Copyright Apple Computer Inc., 1983-1992.  Copyright SVS Inc., 1981.

    LinkIIGS: MPW IIGS Linker -- Version 1.2, Feb 26 1992
    Copyright Apple Computer, Inc. 1987-1992
    All Rights Reserved

**Comment by steventroughtonsmith** [comment]
Good question - 1.0b1, was trying the PascalIIGS from the APDA software library disc; are there more-appropriate releases one should use?

**Comment by ksherlock** [comment]
$aded is Pack6/IUTimeString with the auto-pop bit to (real return address is on the stack).  The feature_trap_address_2015 branch now support it correctly.

**Comment by steventroughtonsmith** [comment]
Verified fixed in branch! Can compile successfully, however any Uses import gives me
```
### PascalIIGS - Error 403 Unable to open uses file
```
with 1.0b1.

With newer versions of PascalIIGS on the same file there are no errors, so I don't think its to do with path variables.

```
PROGRAM test;

USES
QuickDraw;

BEGIN
	WRITELN('Test IIGS')
END.
```

**Comment by ksherlock** [comment]
It needs a `PIIGSincludes` (lowercase i includes) environment variable set up.  Then it needs `User Types, QuickDraw;`.  Then I needed to fix a bug with `SetPtrSize`, but it works now.

**Comment by steventroughtonsmith** [comment]
Verified fixed & can close!

**Comment by ksherlock** [comment]
this has been merged into the master branch now.
