### ISSUE TITLE
Link - Unsupported tool trap: a247 (_SetOSTrapAddress)

### ISSUE THREAD

**Issue by msliczniak** [ksherlock/mpw#25]
$ mpw --trace-toolbox Link foo.c.o
...
a80d Count1Resources(434f4445 ('CODE'))
a99b SetResLoad(0100)
a346 GetOSTrapAddress($a061 (_MaxBlock))
Unsupported tool trap: a247 (_SetOSTrapAddress)
pc: 00f13d9c

**Comment by ksherlock** [comment]
Which version of Link are you using?

**Comment by msliczniak** [comment]
data 'vers' (1, purgeable) {
    	$"0330 8000 0000 0333 2E33 2133 2E33 20A9"            /* .0?....3.3!3.3 ? */
    	$"4170 706C 6520 436F 6D70 7574 6572 2C20"            /* Apple Computer,  */
    	$"496E 632E 2031 3938 352D 3933"                      /* Inc. 1985-93 */
    };
    
    data 'vers' (2, purgeable) {
    	$"0330 8000 0000 0333 2E33 074D 5057 2033"            /* .0?....3.3.MPW 3 */
    	$"2E33"                                               /* .3 */
    };

**Comment by ksherlock** [comment]
Ok, it should work now.

d48f3c39da631f331cad48787d88be957389445a

**Comment by msliczniak** [comment]
Thank you very much! I will test tomorrow.

I have question, what is the dependency on clang? Is it the emulator code? If I get this project to work with for example m68k instead can your code be relicensed to something other than GPL like MIT?

**Comment by ksherlock** [comment]
Any compiler with c++11 support should work. 

The emulator is the only part that's GPL licensed; everything else is under a BSD license.

**Comment by msliczniak** [comment]
It works excellently now, thank you again!

My build machine runs solaris, cmake barfs early on. It has recent gcc. I'll work on some combno getting mpw to work on FS not HFS, using m68k, and more compilers. 

Is there a better place to discuss your project? Basically this bug is fixed, don't want to clutter it up here.

**Comment by ksherlock** [comment]
You can email me directly ksherlock @ gmail.com or we can create a new issue to discuss cross platform  issues.

**Comment by msliczniak** [comment]
Would you like me to merge this into the branch for https://github.com/ksherlock/mpw/issues/16 or do you have other changes still?

**Comment by ksherlock** [comment]
I've added it to that branch as well.
