### ISSUE TITLE
Compilation under Tiger/gcc-4.9

### ISSUE THREAD

**Issue by tsupplis** [ksherlock/mpw#28]
I just compiled successfully mpw on Tiger without too much difficulty and keeping the changes as minimalistic as possible
- Fixed a coding issue in os_internal.cpp (missing ; on line 124)
- Adjusted some header files (in particular, <cstring>,<algorithm> missing in a few places as per c++11 standard)
- Added an implementation of getline for tiger
- bypassed the problem associated to missing birthtime for tiger

I am looking at making it work now on powerpc, are those changes of interest to you?

**Comment by ksherlock** [comment]
Sure!  Thanks.

**Comment by tsupplis** [comment]
I forked the project and pushed my changes 
https://github.com/tsupplis/mpw/commits/tiger_ppc
I fixed the emulator to work on big endian as well / did a retest on the intel side (I used 10.10).
I did not change the cmake configuration though so compiling on tiger still requires a small update locally.
I use tigerbrew gcc-4.9.2 on 10.4.11

**Comment by ksherlock** [comment]
Thank you!
