### ISSUE TITLE
mpw-make clean doesn't work

### ISSUE THREAD

**Issue by MaddTheSane** [ksherlock/mpw#30]
`mpw-make clean` on the MLTESample example fails with an error:
````
mpw Delete -i -y :obj:MLTESampleCarbon.c.y MLTESampleCarbon 
Unable to find command Delete
$MPW = /Users/***/mpw
$Commands = Users:***:mpw:Tools:,"Users:***:mpw:Scripts:"

command failed with exit code 64
````

Using `mpw make clean` succeeds:
````
Delete -i -y ?
	":obj:MLTESampleCarbon.c.y" ?
	MLTESampleCarbon
````

What would cause the two to behave differently?

**Comment by ksherlock** [comment]
`mpw make` just prints the shell commands, it doesn't actually do anything.  `mpw-make` tries to actually run those commands.

In this case, there is no Delete utility, so it can't run and errors out.  If Delete is a standalone utility, you could put it into your mpw:Tools folder and it might work. If it was built into the mpw shell, I'll need to create a new standalone version I guess.

**Comment by ksherlock** [comment]
I've added a delete command to the [mpw-tools](https://github.com/ksherlock/mpw-tools).  Additionally, mpw-make has been upgraded and split out into it's [own project](https://github.com/ksherlock/mpw-shell). 

between the two, makefiles should work better now.
