### ISSUE TITLE
Help command?

### ISSUE THREAD

**Issue by uliwitness** [ksherlock/mpw#41]
In MPW Shell, you can say `Help Link` or `Help PPCLink` to get syntax information for the tools. I don't know how that works, but it would be cool to have the same information on MacOS X. Is there any chance to add a `mpw --help Link` or something feature that does the same thing?

**Comment by ksherlock** [comment]
There is a help command included as part of https://github.com/ksherlock/mpw-tools. The MPW.Help file needs to be split up (into individual Help/xxx files)  I forgot to mention previously, but there were some GitHub releases that included those tools and the help files, but they were marked pre-release so Github hides them.  I just did a new release with fat binaries and updated tools.
