### ISSUE TITLE
Run MPW scripts

### ISSUE THREAD

**Issue by uliwitness** [ksherlock/mpw#42]
I have a makefile that uses `MakePPCCodeRsrc`, which is in MPW's `Scripts` folder, not an executable. Is there a way to make the MPW emulator run scripts?

**Comment by ksherlock** [comment]
Well, there's [this](https://github.com/ksherlock/mpw-shell) reimplementation of mpw shell that can run scripts.

**Comment by uliwitness** [comment]
Thanks, I'll give that one a try.
