### ISSUE TITLE
How to unpack the sit files from the internet archive?

### ISSUE THREAD

**Issue by mathieutozer** [ksherlock/mpw#62]
Hi, I am trying to figure out how to unpack the files from the internet archive - is there anything anyone would advise? I don't have a network connected classic Mac right now. I tried https://infinitemac.org but the unpacking failed.

**Comment by mathieutozer** [comment]
Ok https://theunarchiver.com unpacked the sit successfully I think, but now I have a .toast file that doesn't seem to be unpack able.

**Comment by mathieutozer** [comment]
Oh nice, infinite Mac mounted them as CDs
<img width="442" alt="Screenshot 2023-08-18 at 2 41 42 PM" src="https://github.com/ksherlock/mpw/assets/18321/8261ae02-897b-4523-b065-f934294e0ba6">

**Comment by mathieutozer** [comment]
Unfortunately now I am having issues getting the files back out to macOS. Anyone have any other ideas?

**Comment by ksherlock** [comment]
MacOS through Mojave (10.14) can mount the ETO .toast files as a normal disk image.  I think 10.15 dropped support for HFS

**Comment by mathieutozer** [comment]
Making a partition to install Sierra, in the mean time, I am managing to stuff the MPW directory into a single file to see if that will help with the export from infinite Mac (it's comically slow!)
<img width="348" alt="Screenshot 2023-08-18 at 4 14 47 PM" src="https://github.com/ksherlock/mpw/assets/18321/9f24e93f-153e-4467-85cb-79f20074abc9">

**Comment by uliwitness** [comment]
You could see if you can get a ZIP or TGZ compressor into your emulator. Most OSes today can still unpack them (though they might produce some "junk" files with extra Mac information that you likely won't need).

**Comment by mathieutozer** [comment]
I ended up picking up an old iMac G4 on Facebook marketplace for free, getting it into working order, filesharing the images over to it (It is running 10.5), unpacking there and then filesharing back to my MacBook 🥵
