### ISSUE TITLE
Output bin files are not executable

### ISSUE THREAD

**Issue by mathieutozer** [ksherlock/mpw#63]
I've managed to follow the guide in the wiki for sillyballs (for PPC anyway, see https://github.com/ksherlock/mpw/issues/38#issuecomment-1686848625) but when I move the /bin/Sillyballs.ppc file to Infinitemac it just is read as a document. I'm trying a different emulator but that is taking some time. It just seems like strange output, is there another step to package it into an app that will run? Is it failing a final packaging step because I am opting out of 68k perhaps?

**Comment by ksherlock** [comment]
I’m on vacation and can’t check anything right now but if it shows up as a document, that sounds like the finder info/file type/creator type is being clobbered when you transfer it into infinite Mac (and the resource fork is probably getting clobbered as well)

**Comment by ksherlock** [comment]
OS X has ‘applesingle’ and ‘macbinary’ commands which can wrap up an extended file for transferring. I’m not sure offhand how to undo them in infinite Mac.

**Comment by mathieutozer** [comment]
Thanks for replying on vacation! I can probably wait. I don't really know how to use those tools especially since I'm not sure what I am looking for! I might try a different MPW version in the meantime.

I'm getting a real 90's ppc laptop with a disk drive tomorrow too so might be able to try my app out on that.
